export const tags = [
  { name: "All", count: 11 },
  { name: "ERP", count: 11 },
  { name: "App", count: 6 },
  { name: "Website", count: 6 },
  { name: "Construction", count: 6 },
  { name: "Construction", count: 6 },
  { name: "Construction", count: 6 },
  { name: "Construction", count: 6 },
  { name: "Construction", count: 6 },
  { name: "Construction", count: 6 },
  { name: "Construction", count: 6 },
  { name: "Construction", count: 6 },
  { name: "ERP", count: 6 },
  { name: "ERP", count: 6 },
  { name: "ERP", count: 6 },
  { name: "ERP", count: 6 },
  { name: "ERP", count: 6 },
  { name: "ERP", count: 6 },
  { name: "ERP", count: 6 },
  { name: "ERP", count: 6 },
  { name: "ERP", count: 6 },
  { name: "ERP", count: 6 },
];
